src/java/entities/Suppliers.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entities;

import java.io.Serializable;
import java.util.Collection;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author 98038064
 */
@Entity
@Table(name = "suppliers")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Suppliers.findAll", query = "SELECT s FROM Suppliers s"),
    @NamedQuery(name = "Suppliers.findBySupplierCode", query = "SELECT s FROM Suppliers s WHERE s.supplierCode = :supplierCode"),
    @NamedQuery(name = "Suppliers.findBySupplierName", query = "SELECT s FROM Suppliers s WHERE s.supplierName = :supplierName")})
public class Suppliers implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "supplier_code")
    private Integer supplierCode;
    @Size(max = 45)
    @Column(name = "supplier_name")
    private String supplierName;
    @JoinColumn(name = "region", referencedColumnName = "region_code")
    @ManyToOne
    private SupplierRegion region;
    @OneToMany(mappedBy = "supplierCode")
    private Collection<Products> productsCollection;

    public Suppliers() {
    }

    public Suppliers(Integer supplierCode) {
        this.supplierCode = supplierCode;
    }

    public Integer getSupplierCode() {
        return supplierCode;
    }

    public void setSupplierCode(Integer supplierCode) {
        this.supplierCode = supplierCode;
    }

    public String getSupplierName() {
        return supplierName;
    }

    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }

    public SupplierRegion getRegion() {
        return region;
    }

    public void setRegion(SupplierRegion region) {
        this.region = region;
    }

    @XmlTransient
    public Collection<Products> getProductsCollection() {
        return productsCollection;
    }

    public void setProductsCollection(Collection<Products> productsCollection) {
        this.productsCollection = productsCollection;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (supplierCode != null ? supplierCode.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Suppliers)) {
            return false;
        }
        Suppliers other = (Suppliers) object;
        if ((this.supplierCode == null && other.supplierCode != null) || (this.supplierCode != null && !this.supplierCode.equals(other.supplierCode))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "entities.Suppliers[ supplierCode=" + supplierCode + " ]";
    }
    
}

src/java/jsf/SuppliersController.java
package jsf;

import entities.Suppliers;
import jsf.util.JsfUtil;
import jsf.util.PaginationHelper;
import jpa.session.SuppliersFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("suppliersController")
@SessionScoped
public class SuppliersController implements Serializable {

    private Suppliers current;
    private DataModel items = null;
    @EJB
    private jpa.session.SuppliersFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public SuppliersController() {
    }

    public Suppliers getSelected() {
        if (current == null) {
            current = new Suppliers();
            selectedItemIndex = -1;
        }
        return current;
    }

    private SuppliersFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Suppliers) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Suppliers();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("SuppliersCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Suppliers) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("SuppliersUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Suppliers) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("SuppliersDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Suppliers getSuppliers(java.lang.Integer id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Suppliers.class)
    public static class SuppliersControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            SuppliersController controller = (SuppliersController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "suppliersController");
            return controller.getSuppliers(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Suppliers) {
                Suppliers o = (Suppliers) object;
                return getStringKey(o.getSupplierCode());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Suppliers.class.getName());
            }
        }

    }

}

web/suppliers/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateSuppliersTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateSuppliersLabel_supplierCode}" for="supplierCode" />
                    <h:inputText id="supplierCode" value="#{suppliersController.selected.supplierCode}" title="#{bundle.CreateSuppliersTitle_supplierCode}" required="true" requiredMessage="#{bundle.CreateSuppliersRequiredMessage_supplierCode}"/>
                    <h:outputLabel value="#{bundle.CreateSuppliersLabel_supplierName}" for="supplierName" />
                    <h:inputText id="supplierName" value="#{suppliersController.selected.supplierName}" title="#{bundle.CreateSuppliersTitle_supplierName}" />
                    <h:outputLabel value="#{bundle.CreateSuppliersLabel_region}" for="region" />
                    <h:selectOneMenu id="region" value="#{suppliersController.selected.region}" title="#{bundle.CreateSuppliersTitle_region}" >
                        <f:selectItems value="#{supplierRegionController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{suppliersController.create}" value="#{bundle.CreateSuppliersSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{suppliersController.prepareList}" value="#{bundle.CreateSuppliersShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateSuppliersIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/suppliers/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditSuppliersTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditSuppliersLabel_supplierCode}" for="supplierCode" />
                    <h:inputText id="supplierCode" value="#{suppliersController.selected.supplierCode}" title="#{bundle.EditSuppliersTitle_supplierCode}" required="true" requiredMessage="#{bundle.EditSuppliersRequiredMessage_supplierCode}"/>
                    <h:outputLabel value="#{bundle.EditSuppliersLabel_supplierName}" for="supplierName" />
                    <h:inputText id="supplierName" value="#{suppliersController.selected.supplierName}" title="#{bundle.EditSuppliersTitle_supplierName}" />
                    <h:outputLabel value="#{bundle.EditSuppliersLabel_region}" for="region" />
                    <h:selectOneMenu id="region" value="#{suppliersController.selected.region}" title="#{bundle.EditSuppliersTitle_region}" >
                        <f:selectItems value="#{supplierRegionController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{suppliersController.update}" value="#{bundle.EditSuppliersSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditSuppliersViewLink}"/>
                <br />
                <h:commandLink action="#{suppliersController.prepareList}" value="#{bundle.EditSuppliersShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditSuppliersIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/suppliers/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListSuppliersTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListSuppliersEmpty}" rendered="#{suppliersController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{suppliersController.items.rowCount > 0}">
                    <h:outputText value="#{suppliersController.pagination.pageFirstItem + 1}..#{suppliersController.pagination.pageLastItem + 1}/#{suppliersController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{suppliersController.previous}" value="#{bundle.Previous} #{suppliersController.pagination.pageSize}" rendered="#{suppliersController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{suppliersController.next}" value="#{bundle.Next} #{suppliersController.pagination.pageSize}" rendered="#{suppliersController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{suppliersController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListSuppliersTitle_supplierCode}"/>
                            </f:facet>
                            <h:outputText value="#{item.supplierCode}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListSuppliersTitle_supplierName}"/>
                            </f:facet>
                            <h:outputText value="#{item.supplierName}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListSuppliersTitle_region}"/>
                            </f:facet>
                            <h:outputText value="#{item.region}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{suppliersController.prepareView}" value="#{bundle.ListSuppliersViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{suppliersController.prepareEdit}" value="#{bundle.ListSuppliersEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{suppliersController.destroy}" value="#{bundle.ListSuppliersDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{suppliersController.prepareCreate}" value="#{bundle.ListSuppliersCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListSuppliersIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/suppliers/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewSuppliersTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewSuppliersLabel_supplierCode}"/>
                    <h:outputText value="#{suppliersController.selected.supplierCode}" title="#{bundle.ViewSuppliersTitle_supplierCode}"/>
                    <h:outputText value="#{bundle.ViewSuppliersLabel_supplierName}"/>
                    <h:outputText value="#{suppliersController.selected.supplierName}" title="#{bundle.ViewSuppliersTitle_supplierName}"/>
                    <h:outputText value="#{bundle.ViewSuppliersLabel_region}"/>
                    <h:outputText value="#{suppliersController.selected.region}" title="#{bundle.ViewSuppliersTitle_region}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{suppliersController.destroyAndView}" value="#{bundle.ViewSuppliersDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewSuppliersEditLink}"/>
                <br />
                <h:commandLink action="#{suppliersController.prepareCreate}" value="#{bundle.ViewSuppliersCreateLink}" />
                <br />
                <h:commandLink action="#{suppliersController.prepareList}" value="#{bundle.ViewSuppliersShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewSuppliersIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>